[2025-04-07T03:43:04.084+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparkStreaming_dag.pyspark_consumer scheduled__2024-12-31T17:00:00+00:00 [queued]>
[2025-04-07T03:43:04.092+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparkStreaming_dag.pyspark_consumer scheduled__2024-12-31T17:00:00+00:00 [queued]>
[2025-04-07T03:43:04.092+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2025-04-07T03:43:04.105+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pyspark_consumer> on 2024-12-31 17:00:00+00:00
[2025-04-07T03:43:04.110+0000] {standard_task_runner.py:57} INFO - Started process 83379 to run task
[2025-04-07T03:43:04.114+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparkStreaming_dag', 'pyspark_consumer', 'scheduled__2024-12-31T17:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/dag_sparkStreamJob.py', '--cfg-path', '/tmp/tmpvws082qj']
[2025-04-07T03:43:04.116+0000] {standard_task_runner.py:85} INFO - Job 215: Subtask pyspark_consumer
[2025-04-07T03:43:04.167+0000] {task_command.py:416} INFO - Running <TaskInstance: sparkStreaming_dag.pyspark_consumer scheduled__2024-12-31T17:00:00+00:00 [running]> on host a6934a850e84
[2025-04-07T03:43:04.245+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparkStreaming_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-31T17:00:00+00:00'
[2025-04-07T03:43:04.247+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-07T03:43:04.247+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-server ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.2 ./kafkaToDelta.py &&                 echo "spark-submit completed." &&         ']
[2025-04-07T03:43:04.267+0000] {subprocess.py:86} INFO - Output:
[2025-04-07T03:43:04.269+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2025-04-07T03:43:04.269+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-07T03:43:04.281+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-07T03:43:04.285+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=sparkStreaming_dag, task_id=pyspark_consumer, execution_date=20241231T170000, start_date=20250407T034304, end_date=20250407T034304
[2025-04-07T03:43:04.298+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 215 for task pyspark_consumer (Bash command failed. The command returned a non-zero exit code 2.; 83379)
[2025-04-07T03:43:04.329+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-07T03:43:04.349+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
